http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  playerStatsAPI:
    host: ${GATEWAY_HOST}
    paths: "/api/*"
  adminAPI:
    host: ${GATEWAY_HOST}
    paths: "/admin/*"
    scopes:
      - "admin"
  websocketAPI:
    host: ${GATEWAY_HOST}
    paths: "/ws/*"
serviceEndpoints:
  playerStatsAPI:
    url: ${PLAYER_STATS_API_URL}
  adminAPI:
    url: "http://localhost:9876"
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - ip-whitelist
  - log
  - oauth2
  - proxy
  - rate-limit
  - request-transformer
  - terminate
pipelines:
  websocketPipeline:
    apiEndpoints:
      - websocketAPI
    policies:
      - ip-whitelist:
          action:
            allowedIPs:
              - "127.0.0.1"
              - "::1"
              - ${WHITELIST_IPv4_PROD-1:-}
              - ${WHITELIST_IPv4_PROD-2:-}
              - ${WHITELIST_IPv6_PROD:-}
            statusCode: 403
            message: "Forbidden"
      - key-auth:
      - rate-limit:
          action:
            max: ${RATE_LIMIT_MAX:-100}
            windowMs: 60000
            rateLimitBy: "${req.hostname}"
      - terminate:
          - action:
              statusCode: 200
              body: 'OK'
  playerStatsPipeline:
    apiEndpoints:
      - playerStatsAPI
    policies:
      - ip-whitelist:
          action:
            allowedIPs:
              - "127.0.0.1"
              - "::1"
              - ${WHITELIST_IPv4_PROD-1:-}
              - ${WHITELIST_IPv4_PROD-2:-}
              - ${WHITELIST_IPv6_PROD:-}
            statusCode: 403
            message: "Forbidden"
      - key-auth:
      - cors:
          action:
            origin: "*"
            methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
            allowedHeaders: ["Content-Type", "Authorization"]
            credentials: true
      - rate-limit:
          action:
            max: ${RATE_LIMIT_MAX:-100}
            windowMs: 60000
            rateLimitBy: "${req.hostname}"
      - proxy:
          action:
            serviceEndpoint: playerStatsAPI
            stripPath: true
  adminPipeline:
    apiEndpoints:
      - adminAPI
    policies:
      - key-auth:
      - proxy:
          action:
            serviceEndpoint: adminAPI
            stripPath: true
