events {}

http {
    map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
    }

    server {
        listen 80;
        server_name _;

        location = /_auth_ws {
            internal;

            proxy_pass https://fantasybaseballgateway.onrender.com/ws/getPlayerNews;

            proxy_http_version 1.1;

            proxy_set_header Host $http_host;
            proxy_set_header Authorization $http_authorization;

            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_pass_request_body off;
            proxy_set_header Content-Length "";
        }

        location /ws/getPlayerNews {
            auth_request /_auth_ws;

            proxy_pass https://fantasybaseballplayerstatsapi.onrender.com/getPlayerNews;

            proxy_http_version 1.1;

            proxy_ssl_server_name on;

            proxy_set_header Host fantasybaseballplayerstatsapi.onrender.com;

            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;

            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            proxy_read_timeout 7d;
            proxy_send_timeout 7d;
            proxy_buffering off;
        }
    }
}